# -*- coding: utf-8 -*-
"""App2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mWwmQ_mQ5GjQm3Cw3t7XvaUIAmT_UE66
"""

import matplotlib
matplotlib.use("Agg")
import streamlit as st
import math, warnings, datetime
import numpy as np
import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from scipy.stats import norm
import yfinance as yf
from zoneinfo import ZoneInfo
warnings.filterwarnings("ignore")

st.set_page_config(page_title="⚡ Quant Terminal", layout="wide",
                   page_icon="⚡", initial_sidebar_state="collapsed")

NY  = ZoneInfo("America/New_York")
NOW = datetime.datetime.now(NY)

# ── THEME ────────────────────────────────────────────────────
BS = dict(primary="#A855F7",light="#D8B4FE",dark="#1E0A2E",mid="#2D1B4E",border="#7C3AED",glow="rgba(168,85,247,0.15)",emoji="🔮",label="BLACK-SCHOLES")
MC = dict(primary="#06B6D4",light="#A5F3FC",dark="#021B2E",mid="#0C2D3E",border="#0891B2",glow="rgba(6,182,212,0.15)",emoji="🎲",label="MONTE CARLO")
BT = dict(primary="#10B981",light="#A7F3D0",dark="#022C22",mid="#064E3B",border="#059669",glow="rgba(16,185,129,0.15)",emoji="🌳",label="BINOMIAL TREE")
CF = dict(primary="#F59E0B",light="#FDE68A",dark="#1C1400",mid="#292000",border="#D97706",glow="rgba(245,158,11,0.15)",emoji="💼",label="CFO SUITE")
QT = dict(primary="#EC4899",light="#FBCFE8",dark="#1F0010",mid="#3B0023",border="#DB2777",glow="rgba(236,72,153,0.15)",emoji="📐",label="QUANT LAB")

st.markdown("""
<style>
  html,body,.stApp{background:#020202!important;color:#E5E7EB;}
  section[data-testid="stSidebar"]{display:none;}
  .block-container{padding-top:0.3rem!important;max-width:100%!important;}
  /* TABS */
  .stTabs [data-baseweb="tab-list"]{background:#020202;border-bottom:1px solid #222;gap:2px;padding:0 4px;}
  .stTabs [data-baseweb="tab"]{background:#0a0a0a;color:#555;border:1px solid #222;
    border-radius:6px 6px 0 0;font-family:monospace;font-weight:bold;padding:8px 16px;font-size:12px;}
  .stTabs [aria-selected="true"]{background:linear-gradient(135deg,#A855F7,#06B6D4)!important;color:#fff!important;border-color:transparent!important;}
  /* BUTTONS */
  .stButton>button{font-family:monospace;font-weight:bold;border:none;border-radius:6px;padding:7px 18px;font-size:13px;transition:all 0.2s;}
  .bs-btn>button{background:linear-gradient(135deg,#7C3AED,#A855F7);color:#fff;}
  .mc-btn>button{background:linear-gradient(135deg,#0891B2,#06B6D4);color:#fff;}
  .bt-btn>button{background:linear-gradient(135deg,#059669,#10B981);color:#fff;}
  .cf-btn>button{background:linear-gradient(135deg,#D97706,#F59E0B);color:#000;}
  .qt-btn>button{background:linear-gradient(135deg,#DB2777,#EC4899);color:#fff;}
  .all-btn>button{background:linear-gradient(135deg,#A855F7,#06B6D4,#10B981);color:#fff;font-size:14px;font-weight:bold;}
  /* LABELS */
  label,.stSlider label,.stNumberInput label,.stSelectbox label{font-family:monospace!important;font-weight:bold!important;font-size:11px!important;color:#888!important;}
  /* INPUT BOXES */
  input,select{background:#0D0D0D!important;color:#E5E7EB!important;border:1px solid #333!important;font-family:monospace!important;border-radius:5px!important;}
  /* MISC */
  h1,h2,h3{font-family:monospace!important;color:#E5E7EB!important;}
  .card{background:#0D0D0D;border:1px solid #1a1a1a;border-radius:8px;padding:12px 16px;font-family:Courier New,monospace;}
  .metric-val{font-size:20px;font-weight:bold;}
  hr{border-color:#111!important;}
</style>""", unsafe_allow_html=True)

# ════════════════════════════════════════════════════════════
#  DATA HELPERS
# ════════════════════════════════════════════════════════════
@st.cache_data(ttl=300)
def batch_quotes(tickers_tuple):
    tickers = list(tickers_tuple)
    result  = {t:dict(price=0.0,chg=0.0,pct=0.0,vol=0) for t in tickers}
    try:
        raw = yf.download(tickers, period="5d", auto_adjust=True, progress=False)
        for tk in tickers:
            try:
                if isinstance(raw.columns, pd.MultiIndex):
                    cl = raw["Close"][tk].dropna()
                    vo = raw["Volume"][tk].dropna() if "Volume" in raw else pd.Series()
                else:
                    cl = raw["Close"].dropna()
                    vo = raw["Volume"].dropna() if "Volume" in raw else pd.Series()
                if len(cl)<2: continue
                p=float(cl.iloc[-1]); pr=float(cl.iloc[-2])
                chg=p-pr; pct=chg/pr*100
                vol=int(vo.iloc[-1]) if len(vo)>0 else 0
                result[tk]=dict(price=p,chg=chg,pct=pct,vol=vol)
            except: pass
    except: pass
    return result

@st.cache_data(ttl=300)
def fetch_ohlcv(ticker, period="3mo"):
    try:
        df = yf.download(ticker, period=period, auto_adjust=True, progress=False)
        if isinstance(df.columns, pd.MultiIndex): df.columns = df.columns.get_level_values(0)
        return df[df["Close"].notna()].copy()
    except: return pd.DataFrame()

@st.cache_data(ttl=200)
def get_news(ticker):
    try: return yf.Ticker(ticker).news[:12] or []
    except: return []

@st.cache_data(ttl=300)
def get_info(ticker):
    try: return yf.Ticker(ticker).info or {}
    except: return {}

def fp(p):
    if p>10000:  return f"{p:,.0f}"
    elif p>100:  return f"{p:,.2f}"
    elif p>1:    return f"{p:.4f}"
    elif p>0:    return f"{p:.6f}"
    return "—"

def fc(c):
    a=abs(c)
    if a>100:   return f"{a:,.2f}"
    elif a>0.1: return f"{a:.4f}"
    return f"{a:.6f}"

# ════════════════════════════════════════════════════════════
#  MATH: OPTIONS
# ════════════════════════════════════════════════════════════
def bs_params(St,K,r,sigma,T,q=0):
    d1=(math.log(St/K)+(r-q+0.5*sigma**2)*T)/(sigma*math.sqrt(T))
    return d1, d1-sigma*math.sqrt(T)

def run_bs(St,K,sigma,T,r,q):
    d1,d2=bs_params(St,K,r,sigma,T,q)
    sc=St*math.exp(-q*T)*norm.cdf(d1)-K*math.exp(-r*T)*norm.cdf(d2)
    sp=K*math.exp(-r*T)*norm.cdf(-d2)-St*math.exp(-q*T)*norm.cdf(-d1)
    dc=math.exp(-r*T)*norm.cdf(d2)
    dp=math.exp(-r*T)*norm.cdf(-d2)
    delta_c=math.exp(-q*T)*norm.cdf(d1); delta_p=-math.exp(-q*T)*norm.cdf(-d1)
    gamma=math.exp(-q*T)*norm.pdf(d1)/(St*sigma*math.sqrt(T))
    vega=St*math.exp(-q*T)*norm.pdf(d1)*math.sqrt(T)/100
    theta_c=(-(St*norm.pdf(d1)*sigma*math.exp(-q*T))/(2*math.sqrt(T))-r*K*math.exp(-r*T)*norm.cdf(d2)+q*St*math.exp(-q*T)*norm.cdf(d1))/365
    theta_p=(-(St*norm.pdf(d1)*sigma*math.exp(-q*T))/(2*math.sqrt(T))+r*K*math.exp(-r*T)*norm.cdf(-d2)-q*St*math.exp(-q*T)*norm.cdf(-d1))/365
    return dict(d1=d1,d2=d2,dc=dc,sc=sc,dp=dp,sp=sp,delta_c=delta_c,delta_p=delta_p,gamma=gamma,vega=vega,theta_c=theta_c,theta_p=theta_p)

def run_mc(St,K,sigma,T,r,reps):
    np.random.seed(42)
    Z=np.random.standard_normal(reps)
    ST=St*np.exp((r-0.5*sigma**2)*T+sigma*np.sqrt(T)*Z)
    d1,d2=bs_params(St,K,r,sigma,T)
    return dict(d1=d1,d2=d2,dc=np.exp(-r*T)*np.mean(ST>K),sc=np.exp(-r*T)*np.mean(np.maximum(ST-K,0)),
                dp=np.exp(-r*T)*np.mean(ST<K),sp=np.exp(-r*T)*np.mean(np.maximum(K-ST,0)),ST=ST,reps=reps)

def run_bt(St,K,sigma,T,r,N):
    dt=T/N; u=math.exp(sigma*math.sqrt(dt)); d=1/u
    p=(math.exp(r*dt)-d)/(u-d)
    ST=np.array([St*(u**j)*(d**(N-j)) for j in range(N+1)])
    cp=np.maximum(ST-K,0); pp=np.maximum(K-ST,0)
    dcp=(ST>K).astype(float); dpp=(ST<K).astype(float)
    for _ in range(N,0,-1):
        cp=np.exp(-r*dt)*(p*cp[1:]+(1-p)*cp[:-1])
        pp=np.exp(-r*dt)*(p*pp[1:]+(1-p)*pp[:-1])
        dcp=np.exp(-r*dt)*(p*dcp[1:]+(1-p)*dcp[:-1])
        dpp=np.exp(-r*dt)*(p*dpp[1:]+(1-p)*dpp[:-1])
    d1,d2=bs_params(St,K,r,sigma,T)
    return dict(d1=d1,d2=d2,dc=dcp[0],sc=cp[0],dp=dpp[0],sp=pp[0])

# ════════════════════════════════════════════════════════════
#  HEADER
# ════════════════════════════════════════════════════════════
st.markdown(f"""
<div style='background:linear-gradient(90deg,#0A0010,#001020,#001A0E);
            padding:14px 24px;border-bottom:1px solid #222;
            display:flex;justify-content:space-between;align-items:center;margin-bottom:0'>
  <div>
    <span style='font-size:24px;font-weight:bold;font-family:monospace;
      background:linear-gradient(90deg,#A855F7,#06B6D4,#10B981,#F59E0B);
      -webkit-background-clip:text;-webkit-text-fill-color:transparent;letter-spacing:3px'>
      ⚡ QUANT TERMINAL
    </span>
    <span style='color:#333;font-family:monospace;font-size:11px;margin-left:12px'>
      Market Intelligence · Options · Quant · CFO Suite
    </span>
  </div>
  <div style='font-family:monospace;font-size:11px;color:#444'>
    {NOW.strftime("%A %b %d, %Y  |  %I:%M %p ET")} &nbsp;|&nbsp;
    <span style='color:#10B981'>● LIVE</span>
  </div>
</div>""", unsafe_allow_html=True)

# ════════════════════════════════════════════════════════════
#  MAIN TABS
# ════════════════════════════════════════════════════════════
T_MARKET, T_SCREEN, T_CHART, T_OPTIONS, T_CFO, T_QUANT = st.tabs([
    "🌍 MARKET OVERVIEW",
    "📡 STOCK SIGNALS",
    "📊 CHART ANALYZER",
    "⚙️ OPTIONS PRICER",
    "💼 CFO CALCULATORS",
    "📐 QUANT LAB"
])

# ════════════════════════════════════════════════════════════
#  TAB 1 — MARKET OVERVIEW (Finviz-style)
# ════════════════════════════════════════════════════════════
with T_MARKET:
    if st.button("🔄 Refresh All",key="ref_mkt"): st.cache_data.clear()

    INDICES = {"S&P 500":"^GSPC","NASDAQ":"^IXIC","Dow Jones":"^DJI","Russell 2K":"^RUT",
               "VIX":"^VIX","10Y Yield":"^TNX","Gold":"GC=F","WTI Oil":"CL=F",
               "BTC":"BTC-USD","EUR/USD":"EURUSD=X","USD/JPY":"USDJPY=X","Silver":"SI=F"}
    with st.spinner("Loading market data..."):
        q = batch_quotes(tuple(INDICES.values()))

    # Top ticker bar
    bar_html = "<div style='display:flex;gap:8px;flex-wrap:wrap;padding:10px 0;margin-bottom:8px'>"
    for name, tk in INDICES.items():
        d = q.get(tk,dict(price=0,chg=0,pct=0))
        col = "#00FF41" if d["chg"]>=0 else "#FF4444"
        sign= "▲" if d["chg"]>=0 else "▼"
        bar_html += (f"<div style='background:#0D0D0D;border:1px solid #1a1a1a;border-radius:6px;"
                     f"padding:7px 12px;font-family:monospace;min-width:120px'>"
                     f"<div style='color:#777;font-size:9px'>{name}</div>"
                     f"<div style='color:#E5E7EB;font-size:13px;font-weight:bold'>{fp(d['price'])}</div>"
                     f"<div style='color:{col};font-size:11px'>{sign}{abs(d['pct']):.2f}%</div></div>")
    bar_html += "</div>"
    st.markdown(bar_html, unsafe_allow_html=True)

    col1, col2 = st.columns([3,2])

    with col1:
        # Market breadth
        advancing = 2007; declining = 3315; total = advancing+declining
        adv_pct = advancing/total*100
        st.markdown(f"""
        <div style='background:#0D0D0D;border:1px solid #1a1a1a;border-radius:8px;padding:14px;margin-bottom:10px'>
          <div style='color:#A855F7;font-family:monospace;font-weight:bold;font-size:12px;margin-bottom:10px'>
            📊 MARKET BREADTH
          </div>
          <div style='display:flex;gap:20px;flex-wrap:wrap'>
            <div>
              <div style='color:#555;font-size:10px;font-family:monospace'>ADVANCING</div>
              <div style='color:#00FF41;font-size:18px;font-weight:bold;font-family:monospace'>{advancing:,}</div>
              <div style='color:#00FF41;font-size:11px'>{adv_pct:.1f}%</div>
            </div>
            <div>
              <div style='color:#555;font-size:10px;font-family:monospace'>DECLINING</div>
              <div style='color:#FF4444;font-size:18px;font-weight:bold;font-family:monospace'>{declining:,}</div>
              <div style='color:#FF4444;font-size:11px'>{100-adv_pct:.1f}%</div>
            </div>
            <div>
              <div style='color:#555;font-size:10px;font-family:monospace'>ABOVE SMA50</div>
              <div style='color:#06B6D4;font-size:18px;font-weight:bold;font-family:monospace'>29.0%</div>
            </div>
            <div>
              <div style='color:#555;font-size:10px;font-family:monospace'>ABOVE SMA200</div>
              <div style='color:#06B6D4;font-size:18px;font-weight:bold;font-family:monospace'>40.8%</div>
            </div>
            <div>
              <div style='color:#555;font-size:10px;font-family:monospace'>NEW HIGH</div>
              <div style='color:#F59E0B;font-size:18px;font-weight:bold;font-family:monospace'>73</div>
            </div>
            <div>
              <div style='color:#555;font-size:10px;font-family:monospace'>NEW LOW</div>
              <div style='color:#FF4444;font-size:18px;font-weight:bold;font-family:monospace'>267</div>
            </div>
          </div>
          <div style='margin-top:10px;background:#111;border-radius:4px;height:10px;overflow:hidden'>
            <div style='background:linear-gradient(90deg,#00FF41,#10B981);height:100%;width:{adv_pct:.1f}%'></div>
          </div>
          <div style='display:flex;justify-content:space-between;font-family:monospace;font-size:9px;color:#555;margin-top:3px'>
            <span>Advancing {adv_pct:.1f}%</span><span>Declining {100-adv_pct:.1f}%</span>
          </div>
        </div>""", unsafe_allow_html=True)

        # Gainers / Losers
        g2a, g2b = st.columns(2)
        GAINERS = [("BIAF",2.12,98.13),("AIFF",2.75,58.05),("SVCO",5.03,52.42),
                   ("ELPW",5.16,43.73),("PLYX",6.36,36.77),("APEI",57.66,21.19)]
        LOSERS  = [("IMMP",0.48,-81.64),("IBG",1.10,-55.28),("CMCT",0.63,-44.31),
                   ("BHAT",0.68,-43.75),("KLC",1.95,-42.65),("CDIO",2.80,-38.60)]
        def signal_table(title, data, color, icon):
            rows=""
            for tk,px,pct in data:
                rows+=f"<tr><td style='color:{color};font-weight:bold;padding:5px 8px'>{tk}</td><td style='color:#E5E7EB;padding:5px 8px'>{px}</td><td style='color:{color};padding:5px 8px'>{pct:+.2f}%</td></tr>"
            return f"""<div style='background:#0D0D0D;border:1px solid #1a1a1a;border-radius:8px;padding:12px;margin-bottom:8px'>
              <div style='color:{color};font-family:monospace;font-weight:bold;font-size:12px;margin-bottom:8px'>{icon} {title}</div>
              <table style='width:100%;border-collapse:collapse;font-family:monospace;font-size:12px'>
              <thead><tr><td style='color:#555;padding:4px 8px;font-size:10px'>TICKER</td><td style='color:#555;padding:4px 8px;font-size:10px'>PRICE</td><td style='color:#555;padding:4px 8px;font-size:10px'>CHG%</td></tr></thead>
              <tbody>{rows}</tbody></table></div>"""
        with g2a: st.markdown(signal_table("TOP GAINERS",GAINERS,"#00FF41","🚀"),unsafe_allow_html=True)
        with g2b: st.markdown(signal_table("TOP LOSERS", LOSERS, "#FF4444","📉"),unsafe_allow_html=True)

    with col2:
        # Futures panel
        FUTURES = {"Crude Oil":("CL=F","99.31","+3.74%","#00FF41"),"Natural Gas":("NG=F","3.13","-3.12%","#FF4444"),
                   "Gold":("GC=F","5,023","-2.00%","#FF4444"),"S&P 500 Fut":("ES=F","6,625","-1.52%","#FF4444"),
                   "Nasdaq Fut":("NQ=F","24,335","-1.76%","#FF4444"),"Dow Fut":("YM=F","46,511","-1.07%","#FF4444")}
        rows=""
        for name,(tk,px,pct,col) in FUTURES.items():
            rows+=f"<tr><td style='color:#E5E7EB;padding:6px 10px;font-weight:bold'>{name}</td><td style='color:#F59E0B;padding:6px 10px'>{px}</td><td style='color:{col};padding:6px 10px'>{pct}</td></tr>"
        st.markdown(f"""<div style='background:#0D0D0D;border:1px solid #1a1a1a;border-radius:8px;padding:12px;margin-bottom:10px'>
          <div style='color:#F59E0B;font-family:monospace;font-weight:bold;font-size:12px;margin-bottom:8px'>⚡ FUTURES</div>
          <table style='width:100%;border-collapse:collapse;font-family:monospace;font-size:12px'><tbody>{rows}</tbody></table></div>""",unsafe_allow_html=True)

        # Economic Calendar
        ECON = [("GDP Price Index QoQ","3.8%","3.7%","3.7%","#F59E0B"),
                ("PCE Price Index YoY","2.8%","2.9%","2.9%","#00FF41"),
                ("Personal Income MoM","0.4%","0.5%","0.3%","#FF4444"),
                ("Michigan Sentiment","55.5","55.0","56.6","#F59E0B"),
                ("JOLTs Job Openings","6.95M","6.70M","6.55M","#00FF41")]
        rows=""
        for ev,act,exp,pr,col in ECON:
            rows+=f"<tr><td style='color:#aaa;padding:5px 8px;font-size:11px'>{ev}</td><td style='color:{col};padding:5px 8px;font-weight:bold'>{act}</td><td style='color:#555;padding:5px 8px'>{exp}</td></tr>"
        st.markdown(f"""<div style='background:#0D0D0D;border:1px solid #1a1a1a;border-radius:8px;padding:12px;margin-bottom:10px'>
          <div style='color:#06B6D4;font-family:monospace;font-weight:bold;font-size:12px;margin-bottom:8px'>📅 ECONOMIC CALENDAR</div>
          <table style='width:100%;border-collapse:collapse;font-family:monospace'>
          <thead><tr><td style='color:#555;padding:4px 8px;font-size:10px'>EVENT</td><td style='color:#555;padding:4px 8px;font-size:10px'>ACTUAL</td><td style='color:#555;padding:4px 8px;font-size:10px'>EXPECTED</td></tr></thead>
          <tbody>{rows}</tbody></table></div>""",unsafe_allow_html=True)

        # Insider trades
        INSIDERS=[("AMR","Courtis Kenneth","Director","Buy","$1.87M","#00FF41"),
                  ("XENE","MORTIMER IAN","CEO","Sale","$403K","#FF4444"),
                  ("VRT","—","—","Prop. Sale","$263M","#FF4444"),
                  ("SVRE","—","—","Buy","$688M","#00FF41")]
        rows=""
        for tk,name,role,txn,val,col in INSIDERS:
            rows+=f"<tr><td style='color:#F59E0B;padding:5px 8px;font-weight:bold'>{tk}</td><td style='color:{col};padding:5px 8px'>{txn}</td><td style='color:#aaa;padding:5px 8px'>{val}</td></tr>"
        st.markdown(f"""<div style='background:#0D0D0D;border:1px solid #1a1a1a;border-radius:8px;padding:12px'>
          <div style='color:#EC4899;font-family:monospace;font-weight:bold;font-size:12px;margin-bottom:8px'>🕵️ INSIDER ACTIVITY</div>
          <table style='width:100%;border-collapse:collapse;font-family:monospace;font-size:12px'><tbody>{rows}</tbody></table></div>""",unsafe_allow_html=True)

# ════════════════════════════════════════════════════════════
#  TAB 2 — STOCK SIGNALS (Finviz screener)
# ════════════════════════════════════════════════════════════
with T_SCREEN:
    st.markdown("<h4 style='color:#A855F7;font-family:monospace'>📡 LIVE STOCK SIGNALS</h4>",unsafe_allow_html=True)
    sc1,sc2,sc3 = st.columns([2,2,8])
    with sc1: screen_tk = st.text_input("Ticker",value="AAPL",key="sc_tk").upper()
    with sc2: screen_per= st.selectbox("Period",["1mo","3mo","6mo","1y"],index=2,key="sc_per")
    with sc3:
        st.markdown("<br>",unsafe_allow_html=True)
        run_screen = st.button("🔍 Analyze Stock",key="run_screen")

    if run_screen or screen_tk:
        with st.spinner(f"Analyzing {screen_tk}..."):
            df = fetch_ohlcv(screen_tk, screen_per)
            info= get_info(screen_tk)
            qd  = batch_quotes((screen_tk,)).get(screen_tk,dict(price=0,chg=0,pct=0,vol=0))
            news= get_news(screen_tk)

        if not df.empty and len(df)>30:
            c=df["Close"]
            # Technicals
            sma20=c.rolling(20).mean().iloc[-1]; sma50=c.rolling(50).mean().iloc[-1] if len(c)>50 else sma20
            ema12=c.ewm(span=12).mean(); ema26=c.ewm(span=26).mean()
            macd_line=(ema12-ema26).iloc[-1]; sig_line=((ema12-ema26).ewm(span=9).mean()).iloc[-1]
            # RSI
            d=c.diff(); g=d.clip(lower=0).rolling(14).mean(); l=(-d.clip(upper=0)).rolling(14).mean()
            rsi_val=float((100-100/(1+g/l.replace(0,np.nan))).iloc[-1])
            # BB
            bb_mid=c.rolling(20).mean().iloc[-1]; bb_std=c.rolling(20).std().iloc[-1]
            bb_up=bb_mid+2*bb_std; bb_lo=bb_mid-2*bb_std
            # 52w
            hi52=float(c.tail(252).max()) if len(c)>252 else float(c.max())
            lo52=float(c.tail(252).min()) if len(c)>252 else float(c.min())
            price=qd["price"]
            # Signal
            signals=[]
            if price>sma20: signals.append(("▲ Above SMA20","#00FF41"))
            else: signals.append(("▼ Below SMA20","#FF4444"))
            if price>sma50: signals.append(("▲ Above SMA50","#00FF41"))
            else: signals.append(("▼ Below SMA50","#FF4444"))
            if macd_line>sig_line: signals.append(("📈 MACD Bullish","#00FF41"))
            else: signals.append(("📉 MACD Bearish","#FF4444"))
            if rsi_val>70: signals.append(("🔴 RSI Overbought","#FF4444"))
            elif rsi_val<30: signals.append(("🟢 RSI Oversold","#00FF41"))
            else: signals.append((f"🟡 RSI Neutral {rsi_val:.1f}","#F59E0B"))
            if price>bb_up: signals.append(("📊 Above BB Upper","#FF4444"))
            elif price<bb_lo: signals.append(("📊 Below BB Lower","#00FF41"))
            else: signals.append(("📊 Inside BB","#06B6D4"))

            # Score
            bull=sum(1 for s,c2 in signals if "#00FF41" in c2)
            bear=sum(1 for s,c2 in signals if "#FF4444" in c2)
            score_col="#00FF41" if bull>bear else ("#FF4444" if bear>bull else "#F59E0B")
            score_label="BULLISH 🐂" if bull>bear else ("BEARISH 🐻" if bear>bull else "NEUTRAL ⚖️")

            sa,sb,sc2,sd = st.columns(4)
            def stat_box(col,label,val,color="#E5E7EB",sub=""):
                col.markdown(f"""<div class='card'><div style='color:#555;font-size:10px'>{label}</div>
                  <div style='color:{color};font-size:20px;font-weight:bold;font-family:monospace'>{val}</div>
                  {"<div style='color:#444;font-size:10px'>"+sub+"</div>" if sub else ""}
                  </div>""",unsafe_allow_html=True)
            stat_box(sa,"PRICE",fp(price),"#F59E0B")
            stat_box(sb,"CHANGE",f"{'▲' if qd['chg']>=0 else '▼'}{fc(qd['chg'])} ({qd['pct']:+.2f}%)",
                     "#00FF41" if qd["chg"]>=0 else "#FF4444")
            stat_box(sc2,"RSI (14)",f"{rsi_val:.1f}",
                     "#FF4444" if rsi_val>70 else ("#00FF41" if rsi_val<30 else "#F59E0B"))
            stat_box(sd,"SIGNAL",score_label,score_col,f"{bull} bull · {bear} bear signals")

            sig_html="<div style='display:flex;flex-wrap:wrap;gap:8px;margin:12px 0'>"
            for s,c2 in signals:
                sig_html+=f"<span style='background:#0D0D0D;color:{c2};border:1px solid {c2}33;padding:5px 12px;border-radius:20px;font-family:monospace;font-size:11px'>{s}</span>"
            sig_html+="</div>"
            st.markdown(sig_html,unsafe_allow_html=True)

            # Key stats from yfinance info
            fundamentals = {
                "Market Cap":   f"${info.get('marketCap',0)/1e9:.1f}B" if info.get('marketCap') else "—",
                "P/E Ratio":    f"{info.get('trailingPE',0):.1f}x" if info.get('trailingPE') else "—",
                "EPS (TTM)":    f"${info.get('trailingEps',0):.2f}" if info.get('trailingEps') else "—",
                "Revenue":      f"${info.get('totalRevenue',0)/1e9:.1f}B" if info.get('totalRevenue') else "—",
                "Profit Margin":f"{info.get('profitMargins',0)*100:.1f}%" if info.get('profitMargins') else "—",
                "52W High":     fp(hi52), "52W Low": fp(lo52),
                "Beta":         f"{info.get('beta',0):.2f}" if info.get('beta') else "—",
                "Div Yield":    f"{info.get('dividendYield',0)*100:.2f}%" if info.get('dividendYield') else "0%",
                "Volume":       f"{qd['vol']:,.0f}",
            }
            fund_html="<div style='display:grid;grid-template-columns:repeat(5,1fr);gap:8px;margin-bottom:12px'>"
            for k,v in fundamentals.items():
                fund_html+=f"<div class='card'><div style='color:#555;font-size:10px'>{k}</div><div style='color:#E5E7EB;font-size:14px;font-weight:bold;font-family:monospace'>{v}</div></div>"
            fund_html+="</div>"
            st.markdown(fund_html,unsafe_allow_html=True)

            # Candlestick mini chart
            d1v,d2v,d3v=st.columns([4,1,2])
            with d1v:
                fig=make_subplots(rows=2,cols=1,shared_xaxes=True,row_heights=[.75,.25],vertical_spacing=0.02)
                fig.add_trace(go.Candlestick(x=df.index,open=df["Open"],high=df["High"],low=df["Low"],close=df["Close"],
                    increasing_line_color="#00FF41",decreasing_line_color="#FF4444",name=screen_tk),row=1,col=1)
                sma20s=c.rolling(20).mean(); sma50s=c.rolling(50).mean()
                fig.add_trace(go.Scatter(x=df.index,y=sma20s,line=dict(color="#F59E0B",width=1.2),name="SMA20"),row=1,col=1)
                fig.add_trace(go.Scatter(x=df.index,y=sma50s,line=dict(color="#06B6D4",width=1.2),name="SMA50"),row=1,col=1)
                bb_mids=c.rolling(20).mean(); bb_stds=c.rolling(20).std()
                fig.add_trace(go.Scatter(x=df.index,y=bb_mids+2*bb_stds,line=dict(color="rgba(168,85,247,0.4)",width=1,dash="dash"),showlegend=False),row=1,col=1)
                fig.add_trace(go.Scatter(x=df.index,y=bb_mids-2*bb_stds,line=dict(color="rgba(168,85,247,0.4)",width=1,dash="dash"),fill="tonexty",fillcolor="rgba(168,85,247,0.03)",showlegend=False),row=1,col=1)
                vcols=["#00FF41" if float(cl)>=float(op) else "#FF4444" for cl,op in zip(df["Close"],df["Open"])]
                fig.add_trace(go.Bar(x=df.index,y=df["Volume"],marker_color=vcols,showlegend=False,opacity=0.6),row=2,col=1)
                fig.update_layout(template="plotly_dark",paper_bgcolor="#020202",plot_bgcolor="#0D0D0D",
                    height=420,xaxis_rangeslider_visible=False,
                    legend=dict(orientation="h",x=0,y=1.05,font=dict(family="Courier New",size=9),bgcolor="rgba(0,0,0,0)"),
                    font=dict(family="Courier New",color="#555"),margin=dict(l=50,r=10,t=30,b=20))
                fig.update_xaxes(gridcolor="#111"); fig.update_yaxes(gridcolor="#111")
                st.plotly_chart(fig,use_container_width=True)

            with d3v:
                if news:
                    st.markdown(f"<div style='color:#A855F7;font-family:monospace;font-weight:bold;font-size:11px;margin-bottom:6px'>📰 {screen_tk} NEWS</div>",unsafe_allow_html=True)
                    for item in news[:6]:
                        try:
                            ct=item.get("content",{}); title=ct.get("title",item.get("title",""))[:70]
                            pub=ct.get("pubDate","")[:10]
                            st.markdown(f"""<div style='background:#0D0D0D;border-left:2px solid #A855F7;
                              padding:6px 10px;margin-bottom:6px;border-radius:0 4px 4px 0;
                              font-family:monospace'>
                              <div style='color:#ccc;font-size:11px;line-height:1.4'>{title}</div>
                              <div style='color:#444;font-size:9px;margin-top:3px'>{pub}</div>
                              </div>""",unsafe_allow_html=True)
                        except: continue

# ════════════════════════════════════════════════════════════
#  TAB 3 — CHART (full technical)
# ════════════════════════════════════════════════════════════
with T_CHART:
    cc1,cc2,_ = st.columns([2,2,8])
    with cc1: chart_tk = st.text_input("Ticker",value="SPY",key="ch_tk").upper()
    with cc2: chart_per= st.selectbox("Period",["1mo","3mo","6mo","1y","2y"],index=2,key="ch_per")
    with st.spinner(f"Building {chart_tk} chart..."):
        df2 = fetch_ohlcv(chart_tk, chart_per)
    if not df2.empty and len(df2)>10:
        c2=df2["Close"]
        d=c2.diff(); g=d.clip(lower=0).rolling(14).mean(); l=(-d.clip(upper=0)).rolling(14).mean()
        df2["RSI"]=100-100/(1+g/l.replace(0,np.nan))
        macd_l=c2.ewm(span=12,min_periods=1).mean()-c2.ewm(span=26,min_periods=1).mean()
        df2["MACD"]=macd_l; df2["SIG"]=macd_l.ewm(span=9,min_periods=1).mean(); df2["HIST"]=macd_l-df2["SIG"]
        df2["BB_UP"]=c2.rolling(20,min_periods=1).mean()+2*c2.rolling(20,min_periods=1).std()
        df2["BB_LO"]=c2.rolling(20,min_periods=1).mean()-2*c2.rolling(20,min_periods=1).std()
        df2["EMA20"]=c2.ewm(span=20,min_periods=1).mean()
        df2["EMA50"]=c2.ewm(span=50,min_periods=1).mean()
        df2=df2.dropna(subset=["Close","Open"])
        last=float(df2["Close"].iloc[-1]); prev=float(df2["Close"].iloc[-2])
        chg=last-prev; pct=chg/prev*100
        ct="#00FF41" if chg>=0 else "#FF4444"; sign="▲" if chg>=0 else "▼"
        fig=make_subplots(rows=4,cols=1,shared_xaxes=True,row_heights=[.50,.15,.18,.17],vertical_spacing=0.02)
        fig.add_trace(go.Candlestick(x=df2.index,open=df2["Open"],high=df2["High"],low=df2["Low"],close=df2["Close"],
            increasing_line_color="#00FF41",decreasing_line_color="#FF4444",name=chart_tk),row=1,col=1)
        fig.add_trace(go.Scatter(x=df2.index,y=df2["BB_UP"],line=dict(color="rgba(168,85,247,0.4)",width=1,dash="dash"),showlegend=False),row=1,col=1)
        fig.add_trace(go.Scatter(x=df2.index,y=df2["BB_LO"],line=dict(color="rgba(168,85,247,0.4)",width=1,dash="dash"),fill="tonexty",fillcolor="rgba(168,85,247,0.04)",showlegend=False),row=1,col=1)
        fig.add_trace(go.Scatter(x=df2.index,y=df2["EMA20"],line=dict(color="#F59E0B",width=1.3),name="EMA20"),row=1,col=1)
        fig.add_trace(go.Scatter(x=df2.index,y=df2["EMA50"],line=dict(color="#06B6D4",width=1.3),name="EMA50"),row=1,col=1)
        vcols=["#00FF41" if float(cl)>=float(op) else "#FF4444" for cl,op in zip(df2["Close"],df2["Open"])]
        fig.add_trace(go.Bar(x=df2.index,y=df2["Volume"],marker_color=vcols,showlegend=False,opacity=0.6),row=2,col=1)
        fig.add_trace(go.Scatter(x=df2.index,y=df2["RSI"],line=dict(color="#06B6D4",width=1.3),showlegend=False),row=3,col=1)
        fig.add_hline(y=70,line=dict(color="#FF4444",dash="dash",width=0.8),row=3,col=1)
        fig.add_hline(y=30,line=dict(color="#00FF41",dash="dash",width=0.8),row=3,col=1)
        hcols=["#00FF41" if v>=0 else "#FF4444" for v in df2["HIST"]]
        fig.add_trace(go.Bar(x=df2.index,y=df2["HIST"],marker_color=hcols,showlegend=False,opacity=0.7),row=4,col=1)
        fig.add_trace(go.Scatter(x=df2.index,y=df2["MACD"],line=dict(color="#06B6D4",width=1.3),name="MACD"),row=4,col=1)
        fig.add_trace(go.Scatter(x=df2.index,y=df2["SIG"], line=dict(color="#A855F7",width=1.3),name="Signal"),row=4,col=1)
        fig.update_layout(template="plotly_dark",paper_bgcolor="#020202",plot_bgcolor="#0D0D0D",
            title=dict(text=f"<b style='color:#A855F7'>{chart_tk}</b>  <span style='color:{ct}'>{fp(last)} {sign}{fc(chg)} ({pct:+.2f}%)</span>",
                       font=dict(family="Courier New",size=14),x=0),
            height=700,xaxis_rangeslider_visible=False,
            legend=dict(orientation="h",x=0,y=1.02,font=dict(family="Courier New",size=9),bgcolor="rgba(0,0,0,0)"),
            font=dict(family="Courier New",color="#555"),margin=dict(l=50,r=20,t=55,b=20))
        fig.update_xaxes(gridcolor="#111"); fig.update_yaxes(gridcolor="#111")
        st.plotly_chart(fig,use_container_width=True)

# ════════════════════════════════════════════════════════════
#  TAB 4 — OPTIONS PRICER
# ════════════════════════════════════════════════════════════
with T_OPTIONS:
    def ph(theme,subtitle):
        return f"""<div style='background:linear-gradient(135deg,{theme["dark"]},{theme["mid"]});
          border:1px solid {theme["border"]};border-radius:8px 8px 0 0;padding:12px 16px;text-align:center;
          box-shadow:0 0 20px {theme["glow"]}'>
          <div style='font-size:20px'>{theme["emoji"]}</div>
          <div style='color:{theme["primary"]};font-family:monospace;font-weight:bold;font-size:14px;
            letter-spacing:2px;margin-top:3px'>{theme["label"]}</div>
          <div style='color:{theme["light"]};font-family:monospace;font-size:10px;opacity:0.5;margin-top:2px'>{subtitle}</div>
          </div>"""

    oc1,oc2,oc3=st.columns(3)
    with oc1:
        st.markdown(ph(BS,"Closed-form analytic"),unsafe_allow_html=True)
        st.markdown(f"<div style='background:{BS['dark']};border:1px solid {BS['border']};border-top:none;border-radius:0 0 8px 8px;padding:14px'>",unsafe_allow_html=True)
        bs_St=st.number_input("📍 Spot",0.01,value=10.0,step=0.5,key="bs2_St",format="%.2f")
        bs_K =st.number_input("🎯 Strike",0.01,value=10.0,step=0.5,key="bs2_K", format="%.2f")
        bs_s =st.slider("📊 σ Volatility",0.01,2.0,0.10,0.01,key="bs2_s",format="%.2f")
        bs_T =st.number_input("⏳ T (years)",0.01,value=2.0,step=0.25,key="bs2_T",format="%.2f")
        bs_r =st.slider("🏦 r Risk-Free",0.0,0.30,0.10,0.005,key="bs2_r",format="%.3f")
        bs_q =st.slider("💰 q Dividend",0.0,0.20,0.0,0.005,key="bs2_q",format="%.3f")
        st.markdown("</div>",unsafe_allow_html=True)
        st.markdown("<div class='bs-btn'>",unsafe_allow_html=True)
        run_bs2=st.button("🔮 Price (BS)",key="run_bs2",use_container_width=True)
        st.markdown("</div>",unsafe_allow_html=True)
    with oc2:
        st.markdown(ph(MC,"Stochastic simulation"),unsafe_allow_html=True)
        st.markdown(f"<div style='background:{MC['dark']};border:1px solid {MC['border']};border-top:none;border-radius:0 0 8px 8px;padding:14px'>",unsafe_allow_html=True)
        mc_St=st.number_input("📍 Spot",0.01,value=10.0,step=0.5,key="mc2_St",format="%.2f")
        mc_K =st.number_input("🎯 Strike",0.01,value=10.0,step=0.5,key="mc2_K", format="%.2f")
        mc_s =st.slider("📊 σ Volatility",0.01,2.0,0.10,0.01,key="mc2_s",format="%.2f")
        mc_T =st.number_input("⏳ T (years)",0.01,value=2.0,step=0.25,key="mc2_T",format="%.2f")
        mc_r =st.slider("🏦 r Risk-Free",0.0,0.30,0.10,0.005,key="mc2_r",format="%.3f")
        mc_rp=st.select_slider("🎰 Reps",[1000,5000,10000,50000,100000],value=10000,key="mc2_rp")
        st.markdown("</div>",unsafe_allow_html=True)
        st.markdown("<div class='mc-btn'>",unsafe_allow_html=True)
        run_mc2=st.button("🎲 Price (MC)",key="run_mc2",use_container_width=True)
        st.markdown("</div>",unsafe_allow_html=True)
    with oc3:
        st.markdown(ph(BT,"Discrete lattice"),unsafe_allow_html=True)
        st.markdown(f"<div style='background:{BT['dark']};border:1px solid {BT['border']};border-top:none;border-radius:0 0 8px 8px;padding:14px'>",unsafe_allow_html=True)
        bt_St=st.number_input("📍 Spot",0.01,value=10.0,step=0.5,key="bt2_St",format="%.2f")
        bt_K =st.number_input("🎯 Strike",0.01,value=10.0,step=0.5,key="bt2_K", format="%.2f")
        bt_s =st.slider("📊 σ Volatility",0.01,2.0,0.10,0.01,key="bt2_s",format="%.2f")
        bt_T =st.number_input("⏳ T (years)",0.01,value=2.0,step=0.25,key="bt2_T",format="%.2f")
        bt_r =st.slider("🏦 r Risk-Free",0.0,0.30,0.10,0.005,key="bt2_r",format="%.3f")
        bt_N =st.select_slider("🌿 Steps N",[50,100,200,500,1000],value=100,key="bt2_N")
        st.markdown("</div>",unsafe_allow_html=True)
        st.markdown("<div class='bt-btn'>",unsafe_allow_html=True)
        run_bt2=st.button("🌳 Price (BT)",key="run_bt2",use_container_width=True)
        st.markdown("</div>",unsafe_allow_html=True)

    st.markdown("<br>",unsafe_allow_html=True)
    _,mc_,_=st.columns([2,3,2])
    with mc_:
        st.markdown("<div class='all-btn'>",unsafe_allow_html=True)
        run_all2=st.button("⚡ COMPARE ALL 3 MODELS",key="run_all2",use_container_width=True)
        st.markdown("</div>",unsafe_allow_html=True)

    def rcard(label,val,theme,hint=""):
        return f"""<div style='background:{theme["mid"]};border:1px solid {theme["border"]};
          border-radius:6px;padding:10px 14px;text-align:center;font-family:Courier New,monospace'>
          <div style='color:{theme["primary"]};font-size:10px;letter-spacing:1px'>{label}</div>
          <div style='color:{theme["light"]};font-size:18px;font-weight:bold'>{val:.5f}</div>
          {"<div style='color:#333;font-size:9px'>"+hint+"</div>" if hint else ""}
          </div>"""

    def show_res(res,theme,name):
        st.markdown(f"""<div style='background:{theme["dark"]};border:1px solid {theme["border"]};
          border-radius:8px;padding:14px;box-shadow:0 0 20px {theme["glow"]};margin-bottom:8px'>
          <div style='color:{theme["primary"]};font-family:monospace;font-weight:bold;margin-bottom:10px'>
            {theme["emoji"]} {name}</div>
          <div style='display:grid;grid-template-columns:repeat(3,1fr);gap:6px'>
            {rcard("d1",     res["d1"], theme,"prob factor")}
            {rcard("d2",     res["d2"], theme,"risk-neutral")}
            {rcard("DIG CALL",res["dc"],theme,"binary call")}
            {rcard("SHR CALL",res["sc"],theme,"vanilla call")}
            {rcard("DIG PUT", res["dp"],theme,"binary put")}
            {rcard("SHR PUT", res["sp"],theme,"vanilla put")}
          </div></div>""",unsafe_allow_html=True)

    rb=rm=rt=None
    if run_bs2 or run_all2:
        try: rb=run_bs(bs_St,bs_K,bs_s,bs_T,bs_r,bs_q)
        except Exception as e: st.error(f"BS: {e}")
    if run_mc2 or run_all2:
        try: rm=run_mc(mc_St,mc_K,mc_s,mc_T,mc_r,mc_rp)
        except Exception as e: st.error(f"MC: {e}")
    if run_bt2 or run_all2:
        try: rt=run_bt(bt_St,bt_K,bt_s,bt_T,bt_r,bt_N)
        except Exception as e: st.error(f"BT: {e}")

    if rb or rm or rt:
        r1,r2,r3=st.columns(3)
        with r1:
            if rb: show_res(rb,BS,"Black-Scholes")
        with r2:
            if rm: show_res(rm,MC,"Monte Carlo")
        with r3:
            if rt: show_res(rt,BT,"Binomial Tree")
        if rb and rm and rt:
            cats=["Digital Call","Share Call","Digital Put","Share Put"]
            fig=go.Figure()
            for res,theme,name in [(rb,BS,"BS"),(rm,MC,"MC"),(rt,BT,"BT")]:
                fig.add_trace(go.Bar(name=f"{theme['emoji']} {name}",x=cats,
                    y=[res["dc"],res["sc"],res["dp"],res["sp"]],marker_color=theme["primary"],opacity=0.85))
            fig.update_layout(barmode="group",template="plotly_dark",paper_bgcolor="#020202",plot_bgcolor="#0D0D0D",
                height=350,legend=dict(orientation="h",x=0,y=1.12,font=dict(family="Courier New",size=11),bgcolor="rgba(0,0,0,0)"),
                font=dict(family="Courier New",color="#555"),margin=dict(l=50,r=20,t=50,b=30))
            fig.update_xaxes(gridcolor="#111"); fig.update_yaxes(gridcolor="#111")
            st.plotly_chart(fig,use_container_width=True)
        if rm and "ST" in rm:
            fig=go.Figure(go.Histogram(x=rm["ST"],nbinsx=100,marker_color=MC["primary"],opacity=0.75))
            fig.add_vline(x=mc_K,line=dict(color="#FFD700",dash="dot",width=2),annotation_text=f"K={mc_K}",annotation_font_color="#FFD700")
            fig.add_vline(x=mc_St,line=dict(color="#aaa",dash="dot",width=1.5),annotation_text=f"St={mc_St}",annotation_font_color="#aaa")
            fig.update_layout(template="plotly_dark",paper_bgcolor="#020202",plot_bgcolor="#0D0D0D",height=320,
                title=dict(text="🎲 MC Distribution",font=dict(family="Courier New",size=12,color=MC["primary"]),x=0),
                font=dict(family="Courier New",color="#555"),margin=dict(l=50,r=20,t=50,b=30))
            fig.update_xaxes(gridcolor="#111"); fig.update_yaxes(gridcolor="#111")
            st.plotly_chart(fig,use_container_width=True)

# ════════════════════════════════════════════════════════════
#  TAB 5 — CFO CALCULATORS
# ════════════════════════════════════════════════════════════
with T_CFO:
    st.markdown(f"<h4 style='color:{CF['primary']};font-family:monospace'>💼 CFO FINANCIAL TOOLKIT</h4>",unsafe_allow_html=True)
    cfo1,cfo2 = st.tabs(["📊 DCF VALUATION","💰 WACC CALCULATOR"])

    # ── DCF ──────────────────────────────────────────────────
    with cfo1:
        st.markdown(f"""<div style='background:{CF["dark"]};border:1px solid {CF["border"]};
          border-radius:8px;padding:14px;margin-bottom:14px'>
          <div style='color:{CF["primary"]};font-family:monospace;font-weight:bold;margin-bottom:4px'>
            📊 DISCOUNTED CASH FLOW (DCF) VALUATION MODEL</div>
          <div style='color:#555;font-family:monospace;font-size:11px'>
            Projects free cash flows and discounts at WACC to determine intrinsic value per share.</div>
          </div>""",unsafe_allow_html=True)
        d1a,d1b,d1c=st.columns(3)
        with d1a:
            dcf_fcf   =st.number_input("💵 Base FCF ($M)",value=500.0,step=50.0,key="dcf_fcf",format="%.1f")
            dcf_gr1   =st.slider("📈 Growth Yr 1-5 (%)",0.0,50.0,15.0,0.5,key="dcf_gr1",format="%.1f")
            dcf_gr2   =st.slider("📈 Growth Yr 6-10 (%)",0.0,30.0,8.0,0.5,key="dcf_gr2",format="%.1f")
        with d1b:
            dcf_tgr   =st.slider("♾️ Terminal Growth (%)",0.0,5.0,2.5,0.1,key="dcf_tgr",format="%.1f")
            dcf_wacc  =st.slider("⚖️ WACC (%)",1.0,25.0,10.0,0.25,key="dcf_wacc",format="%.2f")
            dcf_debt  =st.number_input("🏦 Net Debt ($M)",value=200.0,step=10.0,key="dcf_debt",format="%.1f")
        with d1c:
            dcf_shares=st.number_input("📋 Shares Out (M)",value=100.0,step=5.0,key="dcf_sh",format="%.1f")
            dcf_cash  =st.number_input("💰 Cash ($M)",value=150.0,step=10.0,key="dcf_cash",format="%.1f")
            dcf_margin=st.slider("🎯 Margin of Safety (%)",0.0,40.0,20.0,5.0,key="dcf_mos",format="%.0f")

        if st.button("💼 Run DCF",key="run_dcf",use_container_width=False):
            wacc=dcf_wacc/100; tgr=dcf_tgr/100; gr1=dcf_gr1/100; gr2=dcf_gr2/100
            fcfs=[]; fcf=dcf_fcf
            for yr in range(1,11):
                fcf*=(1+gr1) if yr<=5 else (1+gr2)
                pv=fcf/(1+wacc)**yr
                fcfs.append((yr,fcf,pv))
            terminal_fcf=fcfs[-1][1]*(1+tgr)
            terminal_val =terminal_fcf/(wacc-tgr) if wacc>tgr else 0
            pv_terminal  =terminal_val/(1+wacc)**10
            pv_fcfs      =sum(r[2] for r in fcfs)
            ev           =pv_fcfs+pv_terminal
            equity_val   =ev-dcf_debt+dcf_cash
            intrinsic    =equity_val/dcf_shares if dcf_shares>0 else 0
            mos_price    =intrinsic*(1-dcf_margin/100)

            v1,v2,v3,v4,v5=st.columns(5)
            def vbox(col,label,val,sub="",color=CF["primary"]):
                col.markdown(f"""<div style='background:{CF["mid"]};border:1px solid {CF["border"]};
                  border-radius:6px;padding:12px;text-align:center;font-family:monospace'>
                  <div style='color:#555;font-size:10px'>{label}</div>
                  <div style='color:{color};font-size:20px;font-weight:bold'>{val}</div>
                  {"<div style='color:#444;font-size:10px'>"+sub+"</div>" if sub else ""}
                  </div>""",unsafe_allow_html=True)
            vbox(v1,"PV of FCFs",   f"${pv_fcfs:,.0f}M","10-year DCFs")
            vbox(v2,"PV Terminal",  f"${pv_terminal:,.0f}M",f"TV={terminal_val:,.0f}M")
            vbox(v3,"Enterprise Val",f"${ev:,.0f}M","EV = PV(FCF)+PV(TV)")
            vbox(v4,"Intrinsic /sh",f"${intrinsic:.2f}","per share",CF["light"])
            vbox(v5,"MoS Price",    f"${mos_price:.2f}",f"{dcf_margin:.0f}% discount","#00FF41")

            # Waterfall chart
            yrs=[f"Y{r[0]}" for r in fcfs]+["Terminal","Total EV"]
            vals=[r[2] for r in fcfs]+[pv_terminal,ev]
            bar_c=[CF["primary"]]*10+["#F59E0B","#10B981"]
            fig=go.Figure(go.Bar(x=yrs,y=vals,marker_color=bar_c,opacity=0.85,
                text=[f"${v:,.0f}M" for v in vals],textposition="auto",
                textfont=dict(family="Courier New",size=9)))
            fig.update_layout(template="plotly_dark",paper_bgcolor="#020202",plot_bgcolor="#0D0D0D",
                height=360,title=dict(text="💼 DCF Cash Flow Breakdown",font=dict(family="Courier New",size=13,color=CF["primary"]),x=0),
                font=dict(family="Courier New",color="#555"),margin=dict(l=50,r=20,t=50,b=30))
            fig.update_xaxes(gridcolor="#111"); fig.update_yaxes(gridcolor="#111",title="PV ($M)")
            st.plotly_chart(fig,use_container_width=True)

            # Sensitivity table
            st.markdown(f"<div style='color:{CF['primary']};font-family:monospace;font-weight:bold;margin:10px 0 6px'>📊 SENSITIVITY — Intrinsic Value vs WACC & Terminal Growth</div>",unsafe_allow_html=True)
            waccs=[wacc-0.02,wacc-0.01,wacc,wacc+0.01,wacc+0.02]
            tgrs =[tgr-0.01, tgr,      tgr+0.01,tgr+0.02]
            rows={}
            for tg in tgrs:
                row={}
                for wc in waccs:
                    if wc<=tg: row[f"{wc:.1%}"]=float("inf")
                    else:
                        fcf2=dcf_fcf
                        pv2=0
                        for yr in range(1,11):
                            fcf2*=(1+gr1) if yr<=5 else (1+gr2)
                            pv2+=fcf2/(1+wc)**yr
                        tv2=fcf2*(1+tg)/(wc-tg)
                        ptv2=tv2/(1+wc)**10
                        eq2=(pv2+ptv2)-dcf_debt+dcf_cash
                        row[f"WACC {wc:.1%}"]=f"${eq2/dcf_shares:.2f}"
                rows[f"TGR {tg:.1%}"]=row
            sens_df=pd.DataFrame(rows).T
            st.dataframe(sens_df,use_container_width=True)

    # ── WACC ─────────────────────────────────────────────────
    with cfo2:
        st.markdown(f"""<div style='background:{CF["dark"]};border:1px solid {CF["border"]};
          border-radius:8px;padding:14px;margin-bottom:14px'>
          <div style='color:{CF["primary"]};font-family:monospace;font-weight:bold;margin-bottom:4px'>
            ⚖️ WACC — WEIGHTED AVERAGE COST OF CAPITAL</div>
          <div style='color:#555;font-family:monospace;font-size:11px'>
            WACC = (E/V)×Re + (D/V)×Rd×(1−Tc)  —  the minimum return a company must earn.</div>
          </div>""",unsafe_allow_html=True)
        w1,w2,w3=st.columns(3)
        with w1:
            wacc_e  =st.number_input("💹 Equity ($M)",  value=800.0,step=50.0,key="wacc_e",format="%.1f")
            wacc_d  =st.number_input("🏦 Debt ($M)",    value=200.0,step=50.0,key="wacc_d",format="%.1f")
            wacc_rf =st.slider("🏛️ Risk-Free Rate (%)",0.0,10.0,4.5,0.1,key="wacc_rf",format="%.1f")
        with w2:
            wacc_beta=st.slider("📊 Beta",0.1,3.0,1.2,0.05,key="wacc_beta",format="%.2f")
            wacc_erp =st.slider("📈 Equity Risk Prem (%)",3.0,10.0,5.5,0.1,key="wacc_erp",format="%.1f")
            wacc_rd  =st.slider("💳 Cost of Debt (%)",1.0,15.0,5.0,0.25,key="wacc_rd",format="%.2f")
        with w3:
            wacc_tc  =st.slider("🏛️ Tax Rate (%)",0.0,40.0,21.0,0.5,key="wacc_tc",format="%.1f")

        if st.button("⚖️ Calculate WACC",key="run_wacc"):
            V=wacc_e+wacc_d; E_w=wacc_e/V; D_w=wacc_d/V
            Re=wacc_rf/100+wacc_beta*(wacc_erp/100)
            Rd=wacc_rd/100; Tc=wacc_tc/100
            WACC_val=E_w*Re+D_w*Rd*(1-Tc)

            wc1,wc2,wc3,wc4,wc5=st.columns(5)
            def wbox(col,label,val,sub="",color=CF["primary"]):
                col.markdown(f"""<div style='background:{CF["mid"]};border:1px solid {CF["border"]};
                  border-radius:6px;padding:12px;text-align:center;font-family:monospace'>
                  <div style='color:#555;font-size:10px'>{label}</div>
                  <div style='color:{color};font-size:20px;font-weight:bold'>{val}</div>
                  {"<div style='color:#444;font-size:10px'>"+sub+"</div>" if sub else ""}
                  </div>""",unsafe_allow_html=True)
            wbox(wc1,"WACC",       f"{WACC_val:.2%}","Blended rate",CF["light"])
            wbox(wc2,"Cost of Equity",f"{Re:.2%}",f"CAPM: Rf+β×ERP")
            wbox(wc3,"Cost of Debt", f"{Rd*(1-Tc):.2%}",f"After-tax")
            wbox(wc4,"Equity Weight",f"{E_w:.1%}",f"${wacc_e:,.0f}M")
            wbox(wc5,"Debt Weight",  f"{D_w:.1%}",f"${wacc_d:,.0f}M")

            # Pie chart
            fig=make_subplots(rows=1,cols=2,specs=[[{"type":"pie"},{"type":"bar"}]])
            fig.add_trace(go.Pie(labels=["Equity","Debt"],values=[wacc_e,wacc_d],
                marker_colors=[CF["primary"],"#06B6D4"],hole=0.45,
                textfont=dict(family="Courier New",size=11)),row=1,col=1)
            betas=np.linspace(0.5,2.5,50)
            wacc_bs=[E_w*(wacc_rf/100+b*(wacc_erp/100))+D_w*Rd*(1-Tc) for b in betas]
            fig.add_trace(go.Scatter(x=betas,y=[w*100 for w in wacc_bs],
                line=dict(color=CF["primary"],width=2.5),name="WACC vs β"),row=1,col=2)
            fig.add_vline(x=wacc_beta,line=dict(color="#FFD700",dash="dot",width=1.5),
                annotation_text=f"β={wacc_beta}",annotation_font_color="#FFD700",row=1,col=2)
            fig.update_layout(template="plotly_dark",paper_bgcolor="#020202",plot_bgcolor="#0D0D0D",
                height=360,legend=dict(font=dict(family="Courier New",size=10),bgcolor="rgba(0,0,0,0)"),
                font=dict(family="Courier New",color="#555"),margin=dict(l=50,r=20,t=30,b=30))
            fig.update_xaxes(gridcolor="#111",title_text="Beta",row=1,col=2)
            fig.update_yaxes(gridcolor="#111",title_text="WACC (%)",row=1,col=2)
            st.plotly_chart(fig,use_container_width=True)

# ════════════════════════════════════════════════════════════
#  TAB 6 — QUANT LAB
# ════════════════════════════════════════════════════════════
with T_QUANT:
    st.markdown(f"<h4 style='color:{QT['primary']};font-family:monospace'>📐 QUANT LAB — RISK & PORTFOLIO ANALYTICS</h4>",unsafe_allow_html=True)
    q1tab,q2tab = st.tabs(["📉 VaR & RISK METRICS","🔗 PORTFOLIO OPTIMIZER"])

    # ── VaR ──────────────────────────────────────────────────
    with q1tab:
        st.markdown(f"""<div style='background:{QT["dark"]};border:1px solid {QT["border"]};
          border-radius:8px;padding:14px;margin-bottom:14px'>
          <div style='color:{QT["primary"]};font-family:monospace;font-weight:bold;margin-bottom:4px'>
            📉 VALUE AT RISK (VaR) + CVaR / ES — Risk Measurement Suite</div>
          <div style='color:#555;font-family:monospace;font-size:11px'>
            Parametric VaR, Historical VaR, Monte Carlo VaR, CVaR/Expected Shortfall, Sharpe & Sortino ratios.</div>
          </div>""",unsafe_allow_html=True)

        vq1,vq2,vq3=st.columns(3)
        with vq1:
            var_tk  =st.text_input("📍 Ticker",value="SPY",key="var_tk").upper()
            var_per =st.selectbox("📅 Period",["1y","2y","3y","5y"],index=1,key="var_per")
        with vq2:
            var_port=st.number_input("💵 Portfolio ($)",value=1000000.0,step=50000.0,key="var_port",format="%.0f")
            var_conf=st.select_slider("🎯 Confidence Level",[0.90,0.95,0.99],value=0.95,key="var_conf")
        with vq3:
            var_hrz =st.select_slider("📆 Horizon (days)",[1,5,10,20,30,60],value=1,key="var_hrz")
            var_rf2 =st.slider("🏛️ Risk-Free Rate (%)",0.0,10.0,4.5,0.1,key="var_rf2",format="%.1f")

        if st.button("📉 Calculate VaR & Risk",key="run_var",use_container_width=False):
            with st.spinner(f"Fetching {var_tk} data..."):
                df_v=fetch_ohlcv(var_tk, var_per)
            if not df_v.empty and len(df_v)>30:
                rets=df_v["Close"].pct_change().dropna()
                mu=float(rets.mean()); sig=float(rets.std())
                rf_d=var_rf2/100/252
                # Parametric
                z=norm.ppf(1-var_conf)
                var_p=-(mu+z*sig)*math.sqrt(var_hrz)*var_port
                # Historical
                var_h=-np.percentile(rets,  (1-var_conf)*100)*math.sqrt(var_hrz)*var_port
                # Monte Carlo
                np.random.seed(42)
                mc_rets=np.random.normal(mu,sig,(10000,var_hrz))
                mc_pnl=(np.prod(1+mc_rets,axis=1)-1)*var_port
                var_mc=-np.percentile(mc_pnl,(1-var_conf)*100)
                # CVaR
                cutoff=np.percentile(rets,(1-var_conf)*100)
                cvar=-rets[rets<=cutoff].mean()*math.sqrt(var_hrz)*var_port
                # Ratios
                ann_ret=float(rets.mean()*252)
                ann_vol=float(rets.std()*math.sqrt(252))
                sharpe=(ann_ret-var_rf2/100)/ann_vol if ann_vol>0 else 0
                neg_rets=rets[rets<0]
                sortino=(ann_ret-var_rf2/100)/(float(neg_rets.std())*math.sqrt(252)) if len(neg_rets)>0 else 0
                max_dd_s=((df_v["Close"]/df_v["Close"].cummax())-1).min()*100
                calmar=ann_ret/abs(max_dd_s/100) if max_dd_s!=0 else 0
                skew=float(rets.skew()); kurt=float(rets.kurtosis())

                rc1,rc2,rc3,rc4,rc5,rc6=st.columns(6)
                def rbox(col,label,val,sub="",color=QT["primary"]):
                    col.markdown(f"""<div style='background:{QT["mid"]};border:1px solid {QT["border"]};
                      border-radius:6px;padding:10px;text-align:center;font-family:monospace'>
                      <div style='color:#555;font-size:10px'>{label}</div>
                      <div style='color:{color};font-size:18px;font-weight:bold'>{val}</div>
                      {"<div style='color:#444;font-size:9px'>"+sub+"</div>" if sub else ""}
                      </div>""",unsafe_allow_html=True)
                rbox(rc1,"Param VaR",   f"${var_p:,.0f}", f"{var_conf:.0%} / {var_hrz}d","#FF4444")
                rbox(rc2,"Hist VaR",    f"${var_h:,.0f}", "historical sim","#FF4444")
                rbox(rc3,"MC VaR",      f"${var_mc:,.0f}","10k paths","#FF4444")
                rbox(rc4,"CVaR/ES",     f"${cvar:,.0f}",  "expected shortfall","#EC4899")
                rbox(rc5,"Sharpe",      f"{sharpe:.3f}",  "annualized",QT["primary"])
                rbox(rc6,"Sortino",     f"{sortino:.3f}", "downside only",QT["primary"])

                rc7,rc8,rc9,rc10=st.columns(4)
                rbox(rc7, "Ann Return",  f"{ann_ret:.2%}","",  "#00FF41" if ann_ret>0 else "#FF4444")
                rbox(rc8, "Ann Volatility",f"{ann_vol:.2%}","","#F59E0B")
                rbox(rc9, "Max Drawdown",f"{max_dd_s:.2f}%","","#FF4444")
                rbox(rc10,"Calmar Ratio",f"{calmar:.3f}","retun/maxDD",QT["primary"])

                # Return distribution chart
                fig=make_subplots(rows=1,cols=2,subplot_titles=["Return Distribution","Drawdown History"])
                hist_vals, bin_edges=np.histogram(rets,bins=80)
                bin_centers=(bin_edges[:-1]+bin_edges[1:])/2
                colors=["#FF4444" if b<np.percentile(rets,(1-var_conf)*100) else QT["primary"] for b in bin_centers]
                fig.add_trace(go.Bar(x=bin_centers,y=hist_vals,marker_color=colors,opacity=0.75,showlegend=False),row=1,col=1)
                x_norm=np.linspace(rets.min(),rets.max(),200)
                y_norm=norm.pdf(x_norm,mu,sig)*len(rets)*(bin_edges[1]-bin_edges[0])
                fig.add_trace(go.Scatter(x=x_norm,y=y_norm,line=dict(color="#FFD700",width=2),name="Normal fit"),row=1,col=1)
                fig.add_vline(x=np.percentile(rets,(1-var_conf)*100),
                    line=dict(color="#FF4444",dash="dot",width=1.5),annotation_text=f"VaR {var_conf:.0%}",row=1,col=1)
                drawdown=((df_v["Close"]/df_v["Close"].cummax())-1)*100
                fig.add_trace(go.Scatter(x=df_v.index,y=drawdown,fill="tozeroy",
                    fillcolor="rgba(236,72,153,0.15)",line=dict(color=QT["primary"],width=1.2),showlegend=False),row=1,col=2)
                fig.update_layout(template="plotly_dark",paper_bgcolor="#020202",plot_bgcolor="#0D0D0D",
                    height=380,font=dict(family="Courier New",color="#555"),
                    legend=dict(font=dict(family="Courier New",size=10),bgcolor="rgba(0,0,0,0)"),
                    margin=dict(l=50,r=20,t=50,b=30))
                fig.update_xaxes(gridcolor="#111"); fig.update_yaxes(gridcolor="#111")
                st.plotly_chart(fig,use_container_width=True)

                stats_data={"Metric":["Ann Return","Ann Volatility","Sharpe","Sortino","Max Drawdown","Skewness","Excess Kurtosis","Calmar","Param VaR","CVaR/ES"],
                            "Value":[f"{ann_ret:.2%}",f"{ann_vol:.2%}",f"{sharpe:.4f}",f"{sortino:.4f}",f"{max_dd_s:.2f}%",f"{skew:.4f}",f"{kurt:.4f}",f"{calmar:.4f}",f"${var_p:,.0f}",f"${cvar:,.0f}"]}
                st.dataframe(pd.DataFrame(stats_data).set_index("Metric"),use_container_width=True)

    # ── PORTFOLIO OPTIMIZER ──────────────────────────────────
    with q2tab:
        st.markdown(f"""<div style='background:{QT["dark"]};border:1px solid {QT["border"]};
          border-radius:8px;padding:14px;margin-bottom:14px'>
          <div style='color:{QT["primary"]};font-family:monospace;font-weight:bold;margin-bottom:4px'>
            🔗 MARKOWITZ PORTFOLIO OPTIMIZER — Efficient Frontier</div>
          <div style='color:#555;font-family:monospace;font-size:11px'>
            Simulates 5,000 random portfolios. Finds minimum variance and maximum Sharpe ratio allocations.</div>
          </div>""",unsafe_allow_html=True)

        po1,po2=st.columns([3,1])
        with po1:
            port_tks=st.text_input("📋 Tickers (comma-separated)",
                value="SPY,QQQ,GLD,TLT,BTC-USD",key="port_tks")
        with po2:
            port_per=st.selectbox("Period",["1y","2y","3y"],index=1,key="port_per")
            port_rf3=st.slider("Rf Rate (%)",0.0,10.0,4.5,0.1,key="port_rf3",format="%.1f")

        if st.button("🔗 Optimize Portfolio",key="run_port"):
            tickers=[t.strip().upper() for t in port_tks.split(",") if t.strip()]
            if len(tickers)<2:
                st.error("Enter at least 2 tickers.")
            else:
                with st.spinner("Downloading data & running optimizer..."):
                    try:
                        raw=yf.download(tickers,period=port_per,auto_adjust=True,progress=False)
                        if isinstance(raw.columns,pd.MultiIndex):
                            prices=raw["Close"].dropna(how="all")
                        else:
                            prices=raw[["Close"]].dropna()
                            prices.columns=tickers
                        prices=prices.dropna()
                        rets=prices.pct_change().dropna()
                        mu_v=rets.mean()*252
                        cov=rets.cov()*252
                        rf3=port_rf3/100
                        N=len(tickers); n_port=5000
                        np.random.seed(42)
                        results=np.zeros((3,n_port)); weights_all=[]
                        for i in range(n_port):
                            w=np.random.dirichlet(np.ones(N))
                            weights_all.append(w)
                            r=np.dot(w,mu_v)
                            v=math.sqrt(np.dot(w,np.dot(cov.values,w)))
                            results[0,i]=r; results[1,i]=v; results[2,i]=(r-rf3)/v if v>0 else 0
                        max_sh_idx=results[2].argmax()
                        min_vr_idx=results[1].argmin()
                        w_ms=weights_all[max_sh_idx]
                        w_mv=weights_all[min_vr_idx]

                        # Chart
                        fig=go.Figure()
                        fig.add_trace(go.Scatter(x=results[1],y=results[0],mode="markers",
                            marker=dict(color=results[2],colorscale="Plasma",size=3,opacity=0.6,
                                colorbar=dict(title="Sharpe",thickness=12,len=0.8,
                                              title_font=dict(family="Courier New",size=10))),
                            name="Portfolios",hovertemplate="σ=%{x:.2%}<br>Ret=%{y:.2%}<br>Sharpe=%{marker.color:.2f}"))
                        fig.add_trace(go.Scatter(
                            x=[results[1,max_sh_idx]],y=[results[0,max_sh_idx]],
                            mode="markers+text",marker=dict(color="#FFD700",size=16,symbol="star"),
                            text=["⭐ Max Sharpe"],textposition="top right",
                            textfont=dict(family="Courier New",color="#FFD700"),name="Max Sharpe"))
                        fig.add_trace(go.Scatter(
                            x=[results[1,min_vr_idx]],y=[results[0,min_vr_idx]],
                            mode="markers+text",marker=dict(color="#00FF41",size=16,symbol="diamond"),
                            text=["💎 Min Variance"],textposition="top right",
                            textfont=dict(family="Courier New",color="#00FF41"),name="Min Variance"))
                        fig.update_layout(template="plotly_dark",paper_bgcolor="#020202",plot_bgcolor="#0D0D0D",
                            height=460,title=dict(text="🔗 Efficient Frontier — Markowitz Portfolio Optimization",
                                font=dict(family="Courier New",size=13,color=QT["primary"]),x=0),
                            xaxis=dict(title="Annualized Volatility",tickformat=".1%",gridcolor="#111"),
                            yaxis=dict(title="Annualized Return",tickformat=".1%",gridcolor="#111"),
                            legend=dict(font=dict(family="Courier New",size=11),bgcolor="rgba(0,0,0,0)"),
                            font=dict(family="Courier New",color="#555"),margin=dict(l=60,r=20,t=55,b=40))
                        st.plotly_chart(fig,use_container_width=True)

                        # Allocation tables
                        pa,pb=st.columns(2)
                        def alloc_table(col,title,weights,ret_v,vol_v,sh_v,color):
                            rows=""
                            for t,w in zip(tickers,weights):
                                bar_w=int(w*200)
                                rows+=f"""<tr><td style='color:#E5E7EB;padding:5px 10px;font-weight:bold'>{t}</td>
                                <td style='padding:5px 10px'>
                                  <div style='background:#111;border-radius:2px;height:8px;width:200px;display:inline-block;vertical-align:middle'>
                                    <div style='background:{color};height:8px;width:{bar_w}px;border-radius:2px'></div>
                                  </div></td>
                                <td style='color:{color};padding:5px 10px;font-weight:bold'>{w:.1%}</td></tr>"""
                            col.markdown(f"""<div style='background:#0D0D0D;border:1px solid {color}33;border-radius:8px;padding:12px'>
                              <div style='color:{color};font-family:monospace;font-weight:bold;margin-bottom:8px'>{title}</div>
                              <div style='display:flex;gap:20px;font-family:monospace;font-size:11px;color:#555;margin-bottom:8px'>
                                <span>Return: <b style='color:{color}'>{ret_v:.2%}</b></span>
                                <span>Volatility: <b style='color:{color}'>{vol_v:.2%}</b></span>
                                <span>Sharpe: <b style='color:{color}'>{sh_v:.3f}</b></span>
                              </div>
                              <table style='width:100%;border-collapse:collapse;font-family:monospace;font-size:12px'>
                              <tbody>{rows}</tbody></table></div>""",unsafe_allow_html=True)

                        with pa:
                            alloc_table(pa,"⭐ Maximum Sharpe Portfolio",w_ms,
                                results[0,max_sh_idx],results[1,max_sh_idx],results[2,max_sh_idx],"#FFD700")
                        with pb:
                            alloc_table(pb,"💎 Minimum Variance Portfolio",w_mv,
                                results[0,min_vr_idx],results[1,min_vr_idx],results[2,min_vr_idx],"#00FF41")
                    except Exception as e:
                        st.error(f"❌ Portfolio error: {e}")

st.markdown(f"""
<div style='text-align:center;font-family:monospace;font-size:10px;color:#1a1a1a;
             padding:16px 0;margin-top:20px;border-top:1px solid #0a0a0a'>
  ⚡ QUANT TERMINAL  ·  Market Intelligence · Options Pricer · CFO Suite · Quant Lab  ·  Built with Python + Streamlit + Yahoo Finance
</div>""",unsafe_allow_html=True)