# -*- coding: utf-8 -*-
"""markowitz_lab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DShxJYmQZgiCmWbOBx8Wfmm3PLltphiB
"""

import warnings
warnings.filterwarnings("ignore")

import streamlit as st
import numpy as np
import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt
from scipy.optimize import minimize
import bt

st.set_page_config(page_title="Markowitz Lab", layout="wide")

# ------------------------------------------------------------------------------------
# Sidebar inputs
# ------------------------------------------------------------------------------------
st.sidebar.title("🔬 Markowitz Portfolio Lab")

tickers_default = "AAPL, MSFT, GOOG, AMZN, TSLA, NFLX, PG, NVDA"
tickers_str = st.sidebar.text_input("Tickers (comma separated)", value=tickers_default)
tickers = [t.strip().upper() for t in tickers_str.split(",") if t.strip()]

start_date = st.sidebar.date_input("Start date", value=pd.to_datetime("2019-01-01"))
end_date   = st.sidebar.date_input("End date",   value=pd.to_datetime("2025-05-01"))

n_portfolios = st.sidebar.number_input(
    "Monte Carlo iterations", min_value=1000, max_value=50000,
    value=20000, step=1000
)

risk_free_rate = st.sidebar.number_input(
    "Risk‑free rate (annual, decimal)",
    min_value=0.0, max_value=0.20, value=0.0437, step=0.001, format="%.4f"
)

run_button = st.sidebar.button("Run Markowitz Engine 🚀")

st.title("📈 Full Markowitz Portfolio Lab")

if not run_button:
    st.info("Set your parameters at left and click **Run Markowitz Engine**.")
    st.stop()

# ------------------------------------------------------------------------------------
# 1. DATA DOWNLOAD
# ------------------------------------------------------------------------------------
st.subheader("1. Data download")

with st.spinner("Downloading price data from Yahoo Finance..."):
    data = yf.download(
        tickers, start=start_date, end=end_date,
        auto_adjust=True, progress=False
    )

if data.empty:
    st.error("No data returned. Check tickers or dates.")
    st.stop()

if isinstance(data.columns, pd.MultiIndex):
    field = "Adj Close" if "Adj Close" in data.columns.get_level_values(0) else "Close"
    prices = data[field][[t for t in tickers if t in data[field].columns]].dropna(axis=1)
else:
    field = "Adj Close" if "Adj Close" in data.columns else "Close"
    prices = data[field].to_frame()[[t for t in tickers if t in data.columns]]

available_tickers = list(prices.columns)
st.write("Using tickers:", ", ".join(available_tickers))

# ------------------------------------------------------------------------------------
# 2. RETURNS, COVARIANCE, CORRELATION
# ------------------------------------------------------------------------------------
returns = prices.pct_change().dropna()
mean_annual = returns.mean() * 252
cov_annual  = returns.cov() * 252
std_annual  = np.sqrt(np.diag(cov_annual))
corr_matrix = returns.corr()

col_l, col_r = st.columns(2)
with col_l:
    st.write("Annualized expected returns")
    st.dataframe(mean_annual.to_frame("E[R]"), use_container_width=True)

with col_r:
    st.write("Annualized volatility")
    st.dataframe(pd.Series(std_annual, index=available_tickers, name="σ"), use_container_width=True)

# ------------------------------------------------------------------------------------
# 3. COVARIANCE MATRIX HEATMAP
# ------------------------------------------------------------------------------------
st.subheader("2. Covariance and correlation structure")

max_abs_cov = np.max(np.abs(cov_annual.values))

fig, ax = plt.subplots(figsize=(6, 5))
im = ax.imshow(cov_annual, cmap="RdBu", vmin=-max_abs_cov, vmax=max_abs_cov, aspect="auto")
plt.colorbar(im, ax=ax, label="Covariance")
ax.set_xticks(range(len(available_tickers)))
ax.set_yticks(range(len(available_tickers)))
ax.set_xticklabels(available_tickers, rotation=45, ha="right")
ax.set_yticklabels(available_tickers)
ax.set_title("Annualized Covariance Matrix")

for i in range(len(available_tickers)):
    for j in range(len(available_tickers)):
        val = cov_annual.iloc[i, j]
        color = "white" if abs(val) < 0.5 * max_abs_cov else "black"
        ax.text(j, i, f"{val:.2e}", ha="center", va="center", color=color, fontsize=7)

st.pyplot(fig, clear_figure=True)

# ------------------------------------------------------------------------------------
# 4. CORRELATION MATRIX HEATMAP
# ------------------------------------------------------------------------------------
fig, ax = plt.subplots(figsize=(6, 5))
im = ax.imshow(corr_matrix, cmap="RdBu", vmin=-1, vmax=1, aspect="auto")
plt.colorbar(im, ax=ax, label="Correlation")
ax.set_xticks(range(len(available_tickers)))
ax.set_yticks(range(len(available_tickers)))
ax.set_xticklabels(available_tickers, rotation=45, ha="right")
ax.set_yticklabels(available_tickers)
ax.set_title("Asset Correlation Matrix")

for i in range(len(available_tickers)):
    for j in range(len(available_tickers)):
        val = corr_matrix.iloc[i, j]
        color = "white" if abs(val) > 0.5 else "black"
        ax.text(j, i, f"{val:.2f}", ha="center", va="center", color=color, fontsize=8)

st.pyplot(fig, clear_figure=True)

# ------------------------------------------------------------------------------------
# 5. INDIVIDUAL ASSET RISK–RETURN
# ------------------------------------------------------------------------------------
st.subheader("3. Individual asset risk–return")

fig, ax = plt.subplots(figsize=(6, 5))
ax.scatter(std_annual, mean_annual, s=150, color="dodgerblue",
           edgecolor="black", linewidth=2, alpha=0.8)

for i, ticker in enumerate(available_tickers):
    ax.annotate(ticker, (std_annual[i], mean_annual[i]),
                xytext=(6, 6), textcoords="offset points",
                fontweight="bold", fontsize=7)

ax.set_title("Individual Asset Risk–Return (Annualized)")
ax.set_xlabel("Volatility (σ)")
ax.set_ylabel("Expected Return")
ax.grid(True, alpha=0.3)
st.pyplot(fig, clear_figure=True)

# ------------------------------------------------------------------------------------
# 6. MONTE CARLO PORTFOLIO SIMULATION
# ------------------------------------------------------------------------------------
st.subheader("4. Monte Carlo portfolios")

years = (pd.to_datetime(end_date) - pd.to_datetime(start_date)).days / 365.25
n_assets = len(available_tickers)

results = np.zeros((4 + n_assets, n_portfolios))

for i in range(n_portfolios):
    w = np.random.dirichlet(np.ones(n_assets))
    port_ret = float(np.dot(w, mean_annual))
    port_vol = float(np.sqrt(w @ cov_annual.values @ w))

    results[0, i] = port_ret
    results[1, i] = port_vol
    results[2, i] = (port_ret - risk_free_rate) / port_vol if port_vol > 0 else 0.0
    results[3, i] = (1 + port_ret) ** (1 / years) - 1
    results[4:, i] = w

# ------------------------------------------------------------------------------------
# 7. EFFICIENT FRONTIER (optimization)
# ------------------------------------------------------------------------------------
def portfolio_stats(weights, mean_ret, cov):
    port_ret = float(np.dot(weights, mean_ret))
    port_vol = float(np.sqrt(weights @ cov.values @ weights))
    return port_ret, port_vol

def minimize_volatility(mean_ret, cov):
    n = len(mean_ret)
    cons = ({"type": "eq", "fun": lambda x: np.sum(x) - 1},)
    bounds = tuple((0, 1) for _ in range(n))
    res = minimize(lambda w: portfolio_stats(w, mean_ret, cov)[1],
                   n * [1.0 / n], bounds=bounds, constraints=cons)
    return res.x

def maximize_sharpe(mean_ret, cov, rf):
    n = len(mean_ret)
    cons = ({"type": "eq", "fun": lambda x: np.sum(x) - 1},)
    bounds = tuple((0, 1) for _ in range(n))

    def neg_sharpe(w):
        pret, pvol = portfolio_stats(w, mean_ret, cov)
        return -((pret - rf) / pvol)

    res = minimize(neg_sharpe, n * [1.0 / n], bounds=bounds, constraints=cons)
    return res.x

min_vol_weights = minimize_volatility(mean_annual, cov_annual)
min_vol_ret, min_vol_vol = portfolio_stats(min_vol_weights, mean_annual, cov_annual)

tangency_weights = maximize_sharpe(mean_annual, cov_annual, risk_free_rate)
tangency_ret, tangency_vol = portfolio_stats(tangency_weights, mean_annual, cov_annual)

# Efficient frontier curve
target_returns = np.linspace(min_vol_ret, mean_annual.max() * 0.95, 150)
frontier_vols = []
frontier_rets = []

for target in target_returns:
    try:
        cons = [
            {"type": "eq", "fun": lambda x: np.sum(x) - 1},
            {"type": "eq", "fun": lambda x, tgt=target: portfolio_stats(x, mean_annual, cov_annual)[0] - tgt},
        ]
        bounds = tuple((0, 1) for _ in range(n_assets))
        x0 = min_vol_weights.copy()
        res = minimize(
            lambda w: portfolio_stats(w, mean_annual, cov_annual)[1],
            x0,
            bounds=bounds,
            constraints=cons,
            method="SLSQP",
            options={"ftol": 1e-9, "disp": False},
        )
        if res.success and res.fun > 0:
            ret, vol = portfolio_stats(res.x, mean_annual, cov_annual)
            if abs(ret - target) < 1e-6:
                frontier_vols.append(vol)
                frontier_rets.append(ret)
    except Exception:
        continue

frontier_vols = np.array(frontier_vols)
frontier_rets = np.array(frontier_rets)

# ------------------------------------------------------------------------------------
# 8. SCATTER + FRONTIER + CAL
# ------------------------------------------------------------------------------------
st.subheader("5. Efficient frontier and optimal portfolios")

fig, ax = plt.subplots(figsize=(7, 6))

scatter = ax.scatter(
    results[1], results[0],
    c=results[2], cmap="viridis", alpha=0.4, s=15, label="Random Portfolios"
)
cbar = plt.colorbar(scatter, ax=ax)
cbar.set_label("Sharpe Ratio")

if len(frontier_vols) > 0:
    order = np.argsort(frontier_vols)
    ax.plot(frontier_vols[order], frontier_rets[order],
            "b-", linewidth=3, label="Efficient Frontier")

ax.scatter(
    tangency_vol, tangency_ret,
    marker="*", s=350, color="red", edgecolor="black",
    label=f"Tangency (R={tangency_ret:.1%}, σ={tangency_vol:.1%})",
)
ax.scatter(
    min_vol_vol, min_vol_ret,
    marker="*", s=350, color="blue", edgecolor="black",
    label=f"Min Vol (R={min_vol_ret:.1%}, σ={min_vol_vol:.1%})",
)

if len(frontier_vols) > 0:
    cal_x = np.linspace(0, frontier_vols.max() * 1.1, 100)
else:
    cal_x = np.linspace(0, tangency_vol * 2, 100)
cal_y = risk_free_rate + (tangency_ret - risk_free_rate) / tangency_vol * cal_x
ax.plot(cal_x, cal_y, "g--", linewidth=2.5, label="Capital Allocation Line")

ax.set_title("Efficient Frontier Analysis")
ax.set_xlabel("Annualized Volatility")
ax.set_ylabel("Annualized Return")
ax.legend(fontsize=8)
ax.grid(True, alpha=0.3)
st.pyplot(fig, clear_figure=True)

# ------------------------------------------------------------------------------------
# 9. PORTFOLIO ALLOCATIONS (pie charts)
# ------------------------------------------------------------------------------------
st.subheader("6. Optimal portfolio allocations")

fig, axes = plt.subplots(1, 2, figsize=(10, 4))

for ax, (name, w) in zip(
    axes,
    [("Tangency", tangency_weights), ("Min Vol", min_vol_weights)],
):
    mask = w > 0.01
    wedges, texts, autotexts = ax.pie(
        w[mask],
        labels=np.array(available_tickers)[mask],
        autopct="%1.1f%%",
        startangle=90,
        colors=plt.cm.Blues(np.linspace(0.3, 0.9, mask.sum())),
    )
    for autotext in autotexts:
        autotext.set_color("black")
    ax.set_title(name)

st.pyplot(fig, clear_figure=True)

# ------------------------------------------------------------------------------------
# 10. PRICE WITH SMA PLOTS FOR EACH TICKER
# ------------------------------------------------------------------------------------
st.subheader("7. Price with SMAs for each ticker")

fig, axes = plt.subplots(
    nrows=len(available_tickers) // 2 + 1,
    ncols=2,
    figsize=(12, 9),
)
axes = axes.flatten()

for i, ticker in enumerate(available_tickers):
    ax = axes[i]
    ax.plot(prices[ticker], label="Price", color="navy")
    ax.plot(prices[ticker].rolling(35).mean(), label="35‑day SMA", linestyle="--", color="darkorange")
    ax.plot(prices[ticker].rolling(150).mean(), label="150‑day SMA", linestyle="-.", color="forestgreen")
    ax.set_title(f"{ticker} Price with Moving Averages", fontsize=9)
    ax.legend(fontsize=7)
    ax.grid(True, alpha=0.3)

for j in range(i + 1, len(axes)):
    axes[j].axis("off")

plt.tight_layout()
st.pyplot(fig, clear_figure=True)

# ------------------------------------------------------------------------------------
# 11. WEIGHT + PRICE/SMA OVERLAY (TANGENCY)
# ------------------------------------------------------------------------------------
st.subheader("8. Tangency weights vs price/SMA overlay")

target_weights_tangency = pd.DataFrame(
    np.tile(tangency_weights, (len(prices), 1)),
    index=prices.index,
    columns=available_tickers,
)

sma_short = prices.rolling(35).mean()
sma_long  = prices.rolling(150).mean()

merge_list = []
colnames = []
for ticker in available_tickers:
    merge_list.extend(
        [target_weights_tangency[ticker], prices[ticker], sma_short[ticker], sma_long[ticker]]
    )
    colnames.extend(
        [f"{ticker}_Weight", f"{ticker}_Price", f"{ticker}_SMA35", f"{ticker}_SMA150"]
    )

tmp = pd.concat(merge_list, axis=1)
tmp.columns = colnames

fig, ax1 = plt.subplots(figsize=(12, 6))
ax2 = ax1.twinx()

colors = plt.cm.tab10.colors
for i, ticker in enumerate(available_tickers):
    c = colors[i % len(colors)]
    ax1.plot(tmp.index, tmp[f"{ticker}_Price"], label=f"{ticker} Price", color=c, alpha=0.6)
    ax1.plot(tmp.index, tmp[f"{ticker}_SMA35"], linestyle="--", label=f"{ticker} SMA35", color=c, alpha=0.3)
    ax1.plot(tmp.index, tmp[f"{ticker}_SMA150"], linestyle="-.", label=f"{ticker} SMA150", color=c, alpha=0.3)
    ax2.plot(tmp.index, tmp[f"{ticker}_Weight"], label=f"{ticker} Weight", color=c, linewidth=2, alpha=0.9)

ax1.set_title("Target Weights and Price/SMA Overlay (Tangency Portfolio)")
ax1.set_xlabel("Date")
ax1.set_ylabel("Price")
ax2.set_ylabel("Portfolio Weight")
ax1.grid(True, alpha=0.3)

lines1, labels1 = ax1.get_legend_handles_labels()
lines2, labels2 = ax2.get_legend_handles_labels()
ax1.legend(lines1 + lines2, labels1 + labels2, loc="upper left", fontsize=8, ncol=2)

plt.tight_layout()
st.pyplot(fig, clear_figure=True)

# ------------------------------------------------------------------------------------
# 12. BT EQUITY CURVES
# ------------------------------------------------------------------------------------
st.subheader("9. Equity curves from bt backtests")

target_weights_minvol = pd.DataFrame(
    np.tile(min_vol_weights, (len(prices), 1)),
    index=prices.index,
    columns=available_tickers,
)

strategy_tangency = bt.Strategy(
    "Tangency", [bt.algos.WeighTarget(target_weights_tangency), bt.algos.Rebalance()]
)
strategy_minvol = bt.Strategy(
    "Min Vol", [bt.algos.WeighTarget(target_weights_minvol), bt.algos.Rebalance()]
)

test_tangency = bt.Backtest(strategy_tangency, prices)
test_minvol = bt.Backtest(strategy_minvol, prices)

res = bt.run(test_tangency, test_minvol)

fig = plt.figure(figsize=(10, 5))
res.plot()
plt.title("Portfolio Equity Curves (Preview)")
plt.ylabel("Portfolio Value")
plt.grid(True, alpha=0.3)
st.pyplot(fig, clear_figure=True)

st.text("Backtest stats:")
st.text(res.display())

# ------------------------------------------------------------------------------------
# 13. MONTE CARLO PERFORMANCE PATHS
# ------------------------------------------------------------------------------------
st.subheader("10. Monte Carlo portfolio performance paths")

n_days = 252
n_samples = 100
sample_indices = np.random.choice(n_portfolios, n_samples, replace=False)
sample_weights = results[4:, sample_indices].T

daily_returns = np.random.multivariate_normal(
    mean_annual / 252,
    cov_annual / 252,
    size=n_days,
)

portfolio_values = np.ones((n_samples, n_days + 1))
for day in range(n_days):
    portfolio_values[:, day + 1] = portfolio_values[:, day] * (1 + sample_weights @ daily_returns[day])

fig, ax = plt.subplots(figsize=(10, 5))
for i in range(n_samples):
    ax.plot(portfolio_values[i], alpha=0.1, color="blue", linewidth=0.8)

ax.set_title("Monte Carlo Portfolio Performance Paths")
ax.set_xlabel("Trading Days")
ax.set_ylabel("Portfolio Value")
ax.grid(True, alpha=0.3)
st.pyplot(fig, clear_figure=True)